package org.asfa.managerasfa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MemberSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberSubscriptionAllPropertiesEquals(MemberSubscription expected, MemberSubscription actual) {
        assertMemberSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertMemberSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberSubscriptionAllUpdatablePropertiesEquals(MemberSubscription expected, MemberSubscription actual) {
        assertMemberSubscriptionUpdatableFieldsEquals(expected, actual);
        assertMemberSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberSubscriptionAutoGeneratedPropertiesEquals(MemberSubscription expected, MemberSubscription actual) {
        assertThat(expected)
            .as("Verify MemberSubscription auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberSubscriptionUpdatableFieldsEquals(MemberSubscription expected, MemberSubscription actual) {
        assertThat(expected)
            .as("Verify MemberSubscription relevant properties")
            .satisfies(e -> assertThat(e.getSubscriptionDate()).as("check subscriptionDate").isEqualTo(actual.getSubscriptionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberSubscriptionUpdatableRelationshipsEquals(MemberSubscription expected, MemberSubscription actual) {
        assertThat(expected)
            .as("Verify MemberSubscription relationships")
            .satisfies(e -> assertThat(e.getPayment()).as("check payment").isEqualTo(actual.getPayment()));
    }
}
